# Generated by Django 4.2 on 2024-09-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성(Man)'), ('W', '여성(Woman)')], max_length=1, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.TextField(blank=True, verbose_name='자기소개'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='닉네임'),
        ),
    ]
