# Generated by Django 4.2 on 2024-09-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_birth_date_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)')], max_length=1, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.TextField(null=True, verbose_name='자기소개'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='닉네임'),
        ),
    ]
